export default {
    containerClickSettings: false,
    viewMediaFiles: false,
    createAssignment: false,
    inviteUser: false,
    selectMedia: false,
    selectWidget: false,
    renameItem: false,
    templateSettings: false,
    templateSettingsType: 'update',
    timelineSettings: false,
    interactiveSettings: false,
    createPlaylistItem: false,
    timelineSelection: {
        type: null,
        obj: {}
    },
    confirmLeaving: false,
    usersModalList: [],
    modalWidgetType: null,
    modalWidgetContent: null,
    deleteContainer: false,
    selectStatMedia: false,
    statSearch: false,
    isModalOpen: false,
    isPdfSelecting: false,
    pdfModalData: {},
    editOrg: false,
    editOrgMode: false,
    editAdmin: false,
    editGroup: false,
    editGroupMode: false,
    editUser: false,
    editUserMode: false,
    customRules: false
}